[package]
name = "ChainMate"
version = "1.0.0"
authors = []

[addresses]
chainmate = "0x0"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aptos_token_objects = "0x4"
aptos_token = "0x3"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework", rev = "main"}
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/move-stdlib", rev = "main"}
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-token/", rev="main" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-token-objects/", rev="main" }

[dev-dependencies]
